### PR TITLE
AMD slow loading fix

### PR DESCRIPTION
**Pull request by rextimmy**
Fixed bug where auto mipmaps where created for compressed textures that already had mip maps.
Fixed getRendererString for OpenGL card profiler.
Added new OpenGL profile templates.

### CODE REVIEW

**Comment by B-Keeper** [comment]
Thanks for your fix. Unfortunately, on my (Mobility) Radeon HD 4200, nothing seems to have changed, loading is still as slow as it was before.

**Comment by rextimmy** [comment]
Damn, fixed the problem on mine. Where exactly does it appear to be really slow when loading? Mine was when loading the datablocks which is obviously when all the textures are loaded. If you run it in debug mode are you getting any "OPENGL AMD:" errors/warnings in the log?

**Comment by B-Keeper** [comment]
During the "Loading Datablocks" stage, when the progress bar is about halfway, it basically hangs for  about 5 minutes.

I'll compile a debug build soon, and check the log.

**Comment by rextimmy** [comment]
Yep same problem at the same spot, it will be when it is loading the the lurker DDS file and most likely nothing will show up in the log.

I am guessing if you go into gfxGLTextureManager.cpp and change all the "glTexParameteri(binding, GL_GENERATE_MIPMAP_SGIS, GL_TRUE);" to have GL_FALSE (in the innerCreateTexture function) it may work ok.

Let me know if this works, it's not a solution but will help identity it further. I actually think i am going to re-write the whole innerCreateTexture function as there are other parts that are technically incomplete too.

**Comment by B-Keeper** [comment]
Yes, you were right. There were no 'OPENGL AMD' warnings/errors in the log, and setting those parameters to GL_FALSE have fixed the issue.

Because the shaders are still failing to compile, I don't know if anything (apart from the HUD) is rendered correctly or not, but at least the mission loads fine now.

Thank you!

(By the way, as an AMD user, do you have any idea about what causes the screen to be rendered upside-down, as described in my previous report?)

**Comment by rextimmy** [comment]
Thanks for the feedback. I'm going to fix up that whole innerCreateTexture function over the next few days.

I believe your other problem is caused by one of the shaders failing to compile, it's in the shaders that the image you see on screen is flipped.

What catalyst driver are you running there? IF you happen to be using an old one on your laptop and you can't find a newer version, I personally use these drivers http://leshcatlabs.net/, anything before Catalyst 13.x IS going to have plenty of troubles with OpenGL.

**Comment by B-Keeper** [comment]
My Catalyst version is 13.9 (AFAIK the final official version, as this card is not supported any more).

As for having problems with older drivers: I have this machine since 2011, and I had no problems with any other OpenGL engines (apart from a strange texture bug when a long, flat surface is observed from a certain angle, but it's still present with the latest driver).

**Comment by rextimmy** [comment]
Hmm very odd indeed, @LuisAntonRebollo  you can see what I mean now about different OpenGL implementations within the same driver set for different models. I have a 5600m and running the same Catalyst version does not produce the upside down error. Luis it was discovered that there was another problem on NVidia cards with the texture filtering so I will close this pull request and work on fixing up that whole innerCreateTexture.

**Pull request closed without merging**
