### PR TITLE
ARB and AMD debug output

### PR DESCRIPTION
**Pull request by rextimmy**
Added ARB_debug_output.
Added AMD_debug_output.
Fixed the OpenGL card profiler to report a consistent name for the getRendererString()
Added profile scripts for OpenGL.

### CODE REVIEW

**Comment by rextimmy** [comment]
Hi Luis,

I have removed the old pull request and broke it up so this one only contains the above stuff, no fixes for amd loading, im still re-doing that one.

**Comment by LuisAntonRebollo** [comment]
I'm not sure but I think the intention of the specs is separate functionalities. Only is a line, I think it would be better to keep it.

No need to close the pull request, you can ammend commits in your local branch and then make a pull -force to override changes in this pull request.

**Comment by LuisAntonRebollo** [comment]
Another important thing, is a good idea that you create a branch for each pull request. If not, future changes are added here (see Readme update commit).

GG has some info about pull request: https://github.com/GarageGames/Torque3D/wiki/How-To:--Submit-A-Pull-Request

**Comment by rextimmy** [comment]
Oh yeah I understand that but I deleted the branch I had set up for this that's why the pull request got closed. I have had a good think about it and the project I'm working on, I'm going to use a Core OpenGL 3.2 profile based gfx device.

**Pull request closed without merging**
